### ISSUE TITLE
ConnectionListener receives CLOSED event on reconnect

### ISSUE THREAD

**Issue by pepijno** [nats-io/stan.java#146] opened 2019-11-22 11:23 UTC
When the nats server is stopped (or the connection is lost) but then is started again, the ConnectionListener of the StreamingConnectionFactory receives a `ConnectionListener.Events.CLOSED` event after the Reconnected event.

This happens from version `2.2.0` and onward. On version `2.1.6` it doesn't happen and on reconnect only the Reconnected event is received.

Is this supposed to happen?

**Comment by sasbury** [comment] 2019-11-22 23:20
I will take a look

**Comment by mvanderblom** [comment] 2020-02-13 09:55
Hi, i'm running into the same issue. Did you find the time to look into it yet?

**Comment by mvanderblom** [comment] 2020-02-13 11:27
Ok, so i've investigated a bit further. The double disconnect also occurs when using just the jnats client. The "connection closed event" is specific to the streaming client though. See attached testcases to illustrate the example. 
[testcases.zip](https://github.com/nats-io/stan.java/files/4198000/testcases.zip)

**Comment by mvanderblom** [comment] 2020-02-13 11:37
The close event originates from this line of code: https://github.com/nats-io/stan.java/blob/master/src/main/java/io/nats/streaming/StreamingConnectionImpl.java#L401

**Comment by mvanderblom** [comment] 2020-02-13 13:16
I'm not sure if it is related or if it is a seprate issue, but it is what caused me to stumble upon this behavior in the first place, so that's why i'm adding it here.

If i add a publisher to the mix and restart NATS while both publisher and subscriber are connected and te publisher is sending messages the following happens: 

- The publisher keeps sending messages -> as expected
- The log reflects that the subscriber has reconnected and resubscribed -> as expected
- The subscriber message callback isn't called after anymore -> unexpected. 

See the modified testcase: 
[NatsStreamingReconnectionTest.zip](https://github.com/nats-io/stan.java/files/4198486/NatsStreamingReconnectionTest.zip)

**Note** To see this behavior i needed to downgrade to 2.1.6 of the streaming library because the latest version sends the unexpected close event after reconnecting.

**Comment by sasbury** [comment] 2020-02-14 18:41
I switched jobs recently so running behind on this, i will try to take a look this weekend.

**Comment by sasbury** [comment] 2020-02-17 21:54
i am pretty sure that this is related to the new ping behavior, i am not sure of the fix, but the close is happening because of a bad ping from during the disconnect or something

**Comment by sasbury** [comment] 2020-02-17 21:55
looking at the ping "error" we get - client has been replaced or is no longer registered - so the issue is maybe an outstanding ping or a valid ping that the server gets mad about because of the reconnect

**Comment by kozlovic** [comment] 2020-02-18 18:38
@mvanderblom Are you running the NATS Streaming server with a persistent store? If not, the default being MEMORY, it is expected that when the server restart, since there is no state recovered, the reconnect would be rejected.

**Comment by mvanderblom** [comment] 2020-02-19 11:00
@kozlovic I was using the in-memory config. I've observed the behavior you describe. When running in memory, the streaming client disconnects after a restart of the server. When i'm running with file based storage, the client reconnects and resubscribes as expected.

I guess that solves my "bug" ;-) Thanks for helping out! 

It might be helpfull to others to describe this behavior in documentation somewhere.
Don't know if it's already documented, but if so, i wasn't able to find it.

https://docs.nats.io/nats-streaming-server/configuring/persistence

**Comment by kozlovic** [comment] 2020-02-19 21:50
@mvanderblom I submitted a PR for the doc [here](https://github.com/nats-io/nats.docs/pull/59). Thanks for the feedback!

**Comment by kozlovic** [comment] 2020-02-19 23:11
The doc PR has been merged and the change is now live. Closing this issue.

**Closed by kozlovic** 2020-02-19 23:11 UTC
